kubectl apply -f dockercred.yml
kubectl apply -f metrics.yml
kubectl apply -f namespace.yml
kubectl apply -f secrets.yml
kubectl apply -f volumes.yml
kubectl apply -f database-service-deployment.yml
kubectl apply -f front-deployment.yml
kubectl apply -f mailer-service-deployment.yml
kubectl apply -f products-service-deployment.yml
kubectl apply -f users-service-deployment.yml