kubectl apply -f dockercred.yml
kubectl apply -f metrics.yml
kubectl apply -f namespace.yml
kubectl apply -f secrets.yml
kubectl apply -f volume-database.yml
kubectl apply -f volume-jenkins.yml
kubectl apply -f volume-products.yml
kubectl apply -f volume-users.yml
kubectl apply -f database-service-deployment.yml
kubectl apply -f front-deployment.yml
kubectl apply -f mailer-service-deployment.yml
kubectl apply -f products-service-deployment.yml
kubectl apply -f users-service-deployment.yml
kubectl apply -f low-priority.yml
kubectl apply -f medium-priority.yml
kubectl apply -f high-priority.yml