kubectl delete -f dockercred.yml
kubectl delete -f metrics.yml
kubectl delete -f namespace.yml
kubectl delete -f secrets.yml
kubectl delete -f volumes.yml
kubectl delete -f database-service-deployment.yml
kubectl delete -f front-deployment.yml
kubectl delete -f mailer-service-deployment.yml
kubectl delete -f products-service-deployment.yml
kubectl delete -f users-service-deployment.yml