kubectl delete -f dockercred.yml
kubectl delete -f metrics.yml
kubectl delete -f namespace.yml
kubectl delete -f secrets.yml
kubectl delete -f volume-database.yml
kubectl delete -f volume-jenkins.yml
kubectl delete -f volume-products.yml
kubectl delete -f volume-users.yml
kubectl delete -f database-service-deployment.yml
kubectl delete -f front-deployment.yml
kubectl delete -f mailer-service-deployment.yml
kubectl delete -f products-service-deployment.yml
kubectl delete -f users-service-deployment.yml
kubectl delete -f low-priority.yml
kubectl delete -f medium-priority.yml
kubectl delete -f high-priority.yml